# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Rss-Feed-SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Kingfisher'
	pod 'FeedKit'

  # Pods for Rss-Feed-SwiftUI

end
